In [19]:
import nibabel as nib
import numpy as np
import os
np.bool = np.bool_



img = nib.load('img2niftiOAS1_0001_MR1_mpr_n4_anon_111_t88_masked_gfc_fseg.nii')
print(type(img))
print(img.affine)

nib.nifti1.save(img, os.getcwd()+'{}'.format(r'\nifti2imgOAS1_0001_MR1_mpr_n4_anon_111_t88_masked_gfc_fseg.img'))
nib.nifti1.save(img, os.getcwd()+'{}'.format(r'\nifti2imgOAS1_0001_MR1_mpr_n4_anon_111_t88_masked_gfc_fseg.hdr'))

<class 'nibabel.nifti1.Nifti1Image'>
[[  -1.     0.     0.    87.5]
 [   0.     1.     0.  -103.5]
 [   0.     0.     1.   -87.5]
 [   0.     0.     0.     1. ]]
