# Introduction to Deep Learning in Python
Learn the fundamentals concepts and terminology used working with converting nifti to HDR images.
This demo is a jupyter notebook, i.e. intended to be run step by step.

Author: Eric Einspänner
<br>
Contributor: Nastaran Takmilhomayouni

First version: 6th of July 2023


Copyright 2023 Clinic of Neuroradiology, Magdeburg, Germany

License: Apache-2.0
    
*This dataset used in this tutorial can be found her: https://github.com/GinZhu/RDST/tree/main/data/OASIS/example/OAS1_0001_MR1/FSL_SEG*

In [6]:
#you can convert .nii to .img
#hdr file will be automatically created!
import nibabel as nib
import numpy as np
import os
np.bool = np.bool_


fname='Data/nifti2img/OAS1_0001_MR1_mpr_n4_anon_111_t88_masked_gfc_fseg.nii'
img = nib.load(fname)
print(type(img))
print(img.affine)

nib.nifti1.save(img,fname.replace('.nii','.img'))
#nib.nifti1.save(img, os.getcwd()+'{}'.format(r'\nifti2imgOAS1_0001_MR1_mpr_n4_anon_111_t88_masked_gfc_fseg.hdr'))

<class 'nibabel.nifti1.Nifti1Image'>
[[  -1.     0.     0.    87.5]
 [   0.     1.     0.  -103.5]
 [   0.     0.     1.   -87.5]
 [   0.     0.     0.     1. ]]


In [8]:
#you can convert .nii to .hdr
#img file will be automatically created!

import nibabel as nib
import numpy as np
import os
np.bool = np.bool_

fname='Data/nifti2hdr/OAS1_0001_MR1_mpr_n4_anon_111_t88_masked_gfc_fseg.nii'
img = nib.load(fname)
print(type(img))
print(img.affine)

nib.nifti1.save(img,fname.replace('.nii','.hdr'))


<class 'nibabel.nifti1.Nifti1Image'>
[[  -1.     0.     0.    87.5]
 [   0.     1.     0.  -103.5]
 [   0.     0.     1.   -87.5]
 [   0.     0.     0.     1. ]]
